### ISSUE TITLE
panic: reflect: call of reflect.Value.Type on zero Value

### ISSUE THREAD

**Issue by komuw** [komuw/kama#25]
```go
package main

import (
	"github.com/komuw/kama"
	"gopkg.in/mgo.v2"
)

func main() {
	var ss *mgo.Session
	kama.Dirp(ss)
}
```
```sh
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go-faketime/src/reflect/value.go:1908 +0x189
github.com/komuw/kama.getKind(0x7700c0, 0x0, 0xc000018650)
	/tmp/gopath982500244/pkg/mod/github.com/komuw/kama@v0.0.3/vars.go:125 +0x115
github.com/komuw/kama.newVari(0x7700c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/gopath982500244/pkg/mod/github.com/komuw/kama@v0.0.3/vars.go:37 +0x134
github.com/komuw/kama.Dir(0x7700c0, 0x0, 0xc000034748, 0x96d880)
	/tmp/gopath982500244/pkg/mod/github.com/komuw/kama@v0.0.3/kama.go:75 +0x485
github.com/komuw/kama.Dirp(0x7700c0, 0x0)
	/tmp/gopath982500244/pkg/mod/github.com/komuw/kama@v0.0.3/kama.go:35 +0x39
main.main()
	/tmp/sandbox858069193/prog.go:10 +0x36
```

**Comment by komuw** [comment]
However this;
```go
package main

import (
	"github.com/komuw/kama"
)

func main() {
	kama.Dirp(nil)
}
```
works out okay
```sh
[
NAME: nil
KIND: ptr
SIGNATURE: [nil]
FIELDS: []
METHODS: []
SNIPPET: nil
]
```
